// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	LinkUserToOrganization(ctx context.Context, arg LinkUserToOrganizationParams) error
}

var _ Querier = (*Queries)(nil)
