// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	uuid_uuid "github.com/google/uuid.UUID"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name, slug
) VALUES (
    $1, $2
) RETURNING id, name, slug, created_at, updated_at, archived_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, full_name
) VALUES (
    $1, $2, $3
) RETURNING id, email, password_hash, full_name, created_at, updated_at, activated_at, archived_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActivatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    u.id, 
    u.email, 
    u.password_hash, 
    u.full_name, 
    u.activated_at, 
    u.archived_at,
    ou.organization_id,
    ou.role as user_role
FROM users u
LEFT JOIN organization_users ou ON u.id = ou.user_id
WHERE u.email = $1 AND u.archived_at IS NULL
`

type GetUserByEmailRow struct {
	ID             uuid_uuid.UUID     `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FullName       string             `json:"full_name"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserRole       NullUserRole       `json:"user_role"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.ActivatedAt,
		&i.ArchivedAt,
		&i.OrganizationID,
		&i.UserRole,
	)
	return i, err
}

const linkUserToOrganization = `-- name: LinkUserToOrganization :exec
INSERT INTO organization_users (
    organization_id, user_id, role
) VALUES (
    $1, $2, $3
)
`

type LinkUserToOrganizationParams struct {
	OrganizationID uuid_uuid.UUID `json:"organization_id"`
	UserID         uuid_uuid.UUID `json:"user_id"`
	Role           UserRole       `json:"role"`
}

func (q *Queries) LinkUserToOrganization(ctx context.Context, arg LinkUserToOrganizationParams) error {
	_, err := q.db.Exec(ctx, linkUserToOrganization, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}
